/* 研修で使用したテーブルの変更に使用したコマンド */
ALTER TABLE `SHAIN_INFO` ADD `SHAIN_AGE` tinyint(4) UNSIGNED COMMENT '年齢' AFTER `SHAIN_NAME_KN`;
INSERT INTO `SHAIN_INFO` VALUES ('0004','田中　賢介','タナカ　ケンスケ',37,'002');
INSERT INTO `SHAIN_INFO` VALUES ('0005','斎藤　佑樹','サイトウ　ユウキ',NULL,'003');
INSERT INTO `SHAIN_INFO` (SHAIN_NO, SHAIN_NAME_KJ, SHAIN_NAME_KN, BUSHO_CD) VALUES ('9999','テスト　太郎','テスト　タロウ','999');
UPDATE `SHAIN_INFO` SET `SHAIN_AGE` = 45 WHERE `SHAIN_NO` = '0001';
UPDATE `SHAIN_INFO` SET `SHAIN_AGE` = 30 WHERE `SHAIN_NO` = '0002';
UPDATE `SHAIN_INFO` SET `SHAIN_AGE` = 24 WHERE `SHAIN_NO` = '0003';
SELECT * FROM SHAIN_INFO;

/* UNIONで使用した顧客情報テーブル */
CREATE TABLE `CUST_INFO` (
  `CUST_NO` char(4) NOT NULL COMMENT '顧客番号',
  `CUST_NAME_KJ` varchar(20) NOT NULL COMMENT '氏名（漢字）',
  `CUST_NAME_KN` varchar(40) NOT NULL COMMENT '氏名（カナ）',
  `CUST_AGE` tinyint(4) UNSIGNED COMMENT '年齢',
  `PREF_CD` char(2) NOT NULL  COMMENT '地域コード',
  PRIMARY KEY (`CUST_NO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `CUST_INFO` VALUES ('0001','樫野　有香','カシノ　ユカ',30,'01',NULL),
('0002','西脇　綾香','ニシワキ　アヤカ',29,'02'),
('0003','大本　彩乃','オオモト　アヤノ',30,'03');
SELECT * FROM CUST_INFO;